version: "3.9"

services:

  # --------------------
  # MONGODB (REQUIRED)
  # --------------------
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # --------------------
  # AUTH SERVICE
  # --------------------
  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081

  # --------------------
  # COURSE SOAP SERVICE
  # --------------------
  course-service:
    build: ./services/course-service
    container_name: course-service
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082

  # --------------------
  # BILLING SOAP SERVICE
  # --------------------
  billing-service:
    build: ./services/billing-service
    container_name: billing-service
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083

  # --------------------
  # STUDENT SERVICE (NODE)
  # --------------------
  student-service:
    build: ./services/student-service
    container_name: student-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/students_db
    depends_on:
      - mongo

  # --------------------
  # GRADE SERVICE (NODE)
  # --------------------
  grade-service:
    build: ./services/grade-service
    container_name: grade-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - MONGO_URI=mongodb://mongo:27017/grades_db
      - JWT_SECRET=MYSECRET
    depends_on:
      - mongo

  # --------------------
  # API GATEWAY
  # --------------------
  api-gateway:
    build: ./services/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    depends_on:
      - auth-service
      - student-service
      - grade-service
      - course-service
      - billing-service

volumes:
  mongo-data:
